from sqlalchemy import select, func

from app.models import Goal, Task
from app.utils import get_error


class TaskService:
    def __init__(self, ctx):
        self.db = ctx.db
        self.user = ctx.require_user()

    async def list_tasks(self, goal_id: int):
        await self._verify_goal_ownership(goal_id)
        result = await self.db.execute(
            select(Task)
            .where(Task.goal_id == goal_id, Task.user_id == self.user.id, Task.status != "DELETED")
            .order_by(Task.sort_order)
        )
        return [self._task_to_dict(t) for t in result.scalars().all()]

    async def create_task(self, goal_id: int, data: dict):
        await self._verify_goal_ownership(goal_id)

        max_order_result = await self.db.execute(
            select(func.coalesce(func.max(Task.sort_order), -1))
            .where(Task.goal_id == goal_id, Task.user_id == self.user.id, Task.status != "DELETED")
        )
        next_order = max_order_result.scalar() + 1

        task = Task(
            goal_id=goal_id,
            user_id=self.user.id,
            text=data["text"],
            description=data.get("description"),
            output=data.get("output"),
            day_of_week=data.get("day_of_week"),
            scheduled_time=data.get("scheduled_time"),
            estimated_minutes=data.get("estimated_minutes"),
            week_number=data.get("week_number"),
            is_auto_generated=data.get("is_auto_generated", False),
            sort_order=next_order,
        )
        self.db.add(task)
        await self.db.flush()
        await self.db.commit()
        return self._task_to_dict(task)

    async def update_task(self, goal_id: int, task_id: int, data: dict):
        task = await self._get_task_or_404(goal_id, task_id)
        for key, value in data.items():
            if hasattr(task, key):
                setattr(task, key, value)
        await self.db.commit()
        return self._task_to_dict(task)

    async def delete_task(self, goal_id: int, task_id: int):
        task = await self._get_task_or_404(goal_id, task_id)
        task.status = "DELETED"
        await self.db.commit()

    async def reorder_tasks(self, goal_id: int, ordered_ids: list):
        await self._verify_goal_ownership(goal_id)
        for index, tid in enumerate(ordered_ids):
            result = await self.db.execute(
                select(Task).where(
                    Task.id == tid, Task.goal_id == goal_id, Task.user_id == self.user.id
                )
            )
            task = result.scalar_one_or_none()
            if task:
                task.sort_order = index
        await self.db.commit()

    async def _verify_goal_ownership(self, goal_id: int):
        result = await self.db.execute(
            select(Goal).where(
                Goal.id == goal_id, Goal.user_id == self.user.id, Goal.status != "DELETED"
            )
        )
        if not result.scalar_one_or_none():
            raise get_error("NOT_FOUND")

    async def _get_task_or_404(self, goal_id: int, task_id: int):
        await self._verify_goal_ownership(goal_id)
        result = await self.db.execute(
            select(Task).where(
                Task.id == task_id, Task.goal_id == goal_id,
                Task.user_id == self.user.id, Task.status != "DELETED"
            )
        )
        task = result.scalar_one_or_none()
        if not task:
            raise get_error("NOT_FOUND")
        return task

    def _task_to_dict(self, task):
        return {
            "id": task.id,
            "goalId": task.goal_id,
            "text": task.text,
            "description": task.description or "",
            "output": task.output or "",
            "estimatedMinutes": task.estimated_minutes,
            "weekNumber": task.week_number,
            "dayOfWeek": task.day_of_week,
            "scheduledTime": task.scheduled_time,
            "status": task.status,
            "sortOrder": task.sort_order,
            "isAutoGenerated": task.is_auto_generated,
            "createdAt": task.created_at.isoformat() if task.created_at else None,
            "updatedAt": task.updated_at.isoformat() if task.updated_at else None,
        }
